### ISSUE TITLE
Installing Requirements.txt calls for dependencies that appear to be deprecated

### ISSUE THREAD

**Issue by davidkartuzinski** [dtaivpp/python-chatbot#1]
**When running in virtual environment Python Version 3.6.5, and using command:
$ pip install -r python-chatbot/requirements.txt

Get the following error:**

x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -g -fdebug-prefix-map=/build/python3.6-EKG1lX/python3.6-3.6.5=. -specs=/usr/share/dpkg/no-pie-compile.specs -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -I/usr/include/python3.6m -I/home/david/Projects/RasaGitClone/rasagitenv/include -I/usr/include/python3.6m -c cymem/cymem.cpp -o build/temp.linux-x86_64-3.6/cymem/cymem.o -O3 -Wno-strict-prototypes -Wno-unused-function
    x86_64-linux-gnu-gcc: error: cymem/cymem.cpp: No such file or directory
    x86_64-linux-gnu-gcc: fatal error: no input files
    compilation terminated.
    error: command 'x86_64-linux-gnu-gcc' failed with exit status 1

    ----------------------------------------
Command "/home/david/Projects/RasaGitClone/rasagitenv/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-lvmx60k2/cymem/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-8fbgdgzv-record/install-record.txt --single-version-externally-managed --compile --install-headers /home/david/Projects/RasaGitClone/rasagitenv/include/site/python3.6/cymem" failed with error code 1 in /tmp/pip-build-lvmx60k2/cymem/

However, no errors outside of a virtual environment.

Tracking down the error messages, I found and followed these instructions: 
[https://stackoverflow.com/questions/22571848/debugging-the-error-gcc-error-x86-64-linux-gnu-gcc-no-such-file-or-directory#22696574](url)

(I found your repo in an effort to learn Rasa btw)

Thanks.

**Comment by davidkartuzinski** [comment]
I ran the requirements.txt install again.  And then it all of a sudden started working. 
Thanks.

**Comment by dtaivpp** [comment]
Hey Kai,

Thanks for your update! I am working now on creating a docker image as this project has quickly become dependency hell. Also, I am cleaning up the codebase today to hopefully make everything a bit more clear. Let me know if you have any more questions though. I am still very much learning Rasa myself. One note is if you are not working on a fairly beefy pc if you load the repo onto a ramdisk it significantly speeds up training by almost 2x. 

Cheers, 

David Tippett

**Comment by davidkartuzinski** [comment]
Hi David,

We are trying to learn Rasa as well. We are building openapprentice.org, the github is here: https://github.com/OpenApprenticeFoundation/openapprentice-website (https://link.getmailspring.com/link/1533661425.local-95cc381a-5efd-v1.3.0-fd741eb7@getmailspring.com/0?redirect=https%3A%2F%2Fgithub.com%2FOpenApprenticeFoundation%2Fopenapprentice-website&recipient=cmVwbHkrMDFjMjJlOGU3MWJlZjU3NzY4MjMyZTNiNDEyMTJhZGI5NjViMGQ1NmY0OTE3YjZhOTJjZjAwMDAwMDAxMTc4MTg5NTI5MmExNjljZTE0YzNlMWMzQHJlcGx5LmdpdGh1Yi5jb20%3D)
We want to use Rasa as a way to help create interactive tutorials. But we're all sort of the blind leading the blind.
One of the guys, Ronan, is having a helluva of a time just setting up a basic Rasa install. Tutuorial after tutorial just are outdated and we don't know enough to resolve.
Would you be willing to walk us through and spend 20-30 minutes answering basic questions that somehow escape our understanding?
Thanks.
-DK
ps. Pretty cool that you set it up. We already answered a bunch of questions just by looking at your code!

**Comment by dtaivpp** [comment]
Hey Kai, 

I would be happy to share my experiences with you all! How soon do you all want to meet (probably not today, but I should have time for tomorrow)? I can set aside an hour to talk. I had the same problem as well which is why I am working on bringing this example up to date and up to current spec with Rasa’s Docs. Just let me know what time works well for you all and I will see how well we can accommodate. 

Cheers, 

David Tippett

**Comment by davidkartuzinski** [comment]
Thanks!I am David btw.  I lived in Taiwan.  So my name in Chinese is Kai DaWei - DaWei is David in Chinese.  Please call me David hahaDo you have discord or Signal?I am in France and Ronan is in Canada. Where are you?If you just help Ronan - then he can teach me.  He is more knowledgeable than I!!  I appreciate it!-dk---- On Tue, 07 Aug 2018 19:12:09 +0200  David Tippett<notifications@github.com> wrote ----Hey Kai,   I would be happy to share my experiences with you all! How soon do you all want to meet (probably not today, but I should have time for tomorrow)? I can set aside an hour to talk. I had the same problem as well which is why I am working on bringing this example up to date and up to current spec with Rasa’s Docs. Just let me know what time works well for you all and I will see how well we can accommodate.   Cheers,   David Tippett  > On Aug 7, 2018, at 1:07 PM, Kai Dawei <notifications@github.com> wrote: >  > Hi David, >  > We are trying to learn Rasa as well. We are building openapprentice.org <http://openapprentice.org/>, the github is here: https://github.com/OpenApprenticeFoundation/openapprentice-website <https://github.com/OpenApprenticeFoundation/openapprentice-website> (https://link.getmailspring.com/link/1533661425.local-95cc381a-5efd-v1.3.0-fd741eb7@getmailspring.com/0?redirect=https%3A%2F%2Fgithub.com%2FOpenApprenticeFoundation%2Fopenapprentice-website&recipient=cmVwbHkrMDFjMjJlOGU3MWJlZjU3NzY4MjMyZTNiNDEyMTJhZGI5NjViMGQ1NmY0OTE3YjZhOTJjZjAwMDAwMDAxMTc4MTg5NTI5MmExNjljZTE0YzNlMWMzQHJlcGx5LmdpdGh1Yi5jb20%3D <https://link.getmailspring.com/link/1533661425.local-95cc381a-5efd-v1.3.0-fd741eb7@getmailspring.com/0?redirect=https%3A%2F%2Fgithub.com%2FOpenApprenticeFoundation%2Fopenapprentice-website&recipient=cmVwbHkrMDFjMjJlOGU3MWJlZjU3NzY4MjMyZTNiNDEyMTJhZGI5NjViMGQ1NmY0OTE3YjZhOTJjZjAwMDAwMDAxMTc4MTg5NTI5MmExNjljZTE0YzNlMWMzQHJlcGx5LmdpdGh1Yi5jb20%3D>) > We want to use Rasa as a way to help create interactive tutorials. But we're all sort of the blind leading the blind. > One of the guys, Ronan, is having a helluva of a time just setting up a basic Rasa install. Tutuorial after tutorial just are outdated and we don't know enough to resolve. > Would you be willing to walk us through and spend 20-30 minutes answering basic questions that somehow escape our understanding? > Thanks. > -DK > ps. Pretty cool that you set it up. We already answered a bunch of questions just by looking at your code! >  > Sent from Mailspring (https://link.getmailspring.com/link/1533661425.local-95cc381a-5efd-v1.3.0-fd741eb7@getmailspring.com/1?redirect=https%3A%2F%2Fgetmailspring.com%2F&recipient=cmVwbHkrMDFjMjJlOGU3MWJlZjU3NzY4MjMyZTNiNDEyMTJhZGI5NjViMGQ1NmY0OTE3YjZhOTJjZjAwMDAwMDAxMTc4MTg5NTI5MmExNjljZTE0YzNlMWMzQHJlcGx5LmdpdGh1Yi5jb20%3D <https://link.getmailspring.com/link/1533661425.local-95cc381a-5efd-v1.3.0-fd741eb7@getmailspring.com/1?redirect=https%3A%2F%2Fgetmailspring.com%2F&recipient=cmVwbHkrMDFjMjJlOGU3MWJlZjU3NzY4MjMyZTNiNDEyMTJhZGI5NjViMGQ1NmY0OTE3YjZhOTJjZjAwMDAwMDAxMTc4MTg5NTI5MmExNjljZTE0YzNlMWMzQHJlcGx5LmdpdGh1Yi5jb20%3D>), the best free email app for work > On Aug 7 2018, at 6:22 pm, David Tippett <notifications@github.com <mailto:notifications@github.com>> wrote: > > > > Hey Kai, > > Thanks for your update! I am working now on creating a docker image as this project has quickly become dependency hell. Also, I am cleaning up the codebase today to hopefully make everything a bit more clear. Let me know if you have any more questions though. I am still very much learning Rasa myself. One note is if you are not working on a fairly beefy pc if you load the repo onto a ramdisk it significantly speeds up training by almost 2x. > > Cheers, > > David Tippett > > > On Aug 7, 2018, at 11:49 AM, Kai Dawei <notifications@github.com <mailto:notifications@github.com>> wrote: > > > > > > **When running in virtual environment Python Version 3.6.5, and using command: > > > $ pip install -r python-chatbot/requirements.txt > > > > > > Get the following error:** > > > > > > x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -g -fdebug-prefix-map=/build/python3.6-EKG1lX/python3.6-3.6.5=. -specs=/usr/share/dpkg/no-pie-compile.specs -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -I/usr/include/python3.6m -I/home/david/Projects/RasaGitClone/rasagitenv/include -I/usr/include/python3.6m -c cymem/cymem.cpp -o build/temp.linux-x86_64-3.6/cymem/cymem.o -O3 -Wno-strict-prototypes -Wno-unused-function > > > x86_64-linux-gnu-gcc: error: cymem/cymem.cpp: No such file or directory > > > x86_64-linux-gnu-gcc: fatal error: no input files > > > compilation terminated. > > > error: command 'x86_64-linux-gnu-gcc' failed with exit status 1 > > > > > > ---------------------------------------- > > > Command "/home/david/Projects/RasaGitClone/rasagitenv/bin/python3 -u -c "import setuptools, tokenize;file='/tmp/pip-build-lvmx60k2/cymem/setup.py';f=getattr(tokenize, 'open', open)(file);code=f.read().replace('
', '

**Comment by dtaivpp** [comment]
David, 

Ah, I am also David! I have discord as well. My tag is Awoo#3711 if you want to connect (please do not judge the tag). I am on mostly between 7 am and 5 pm (utc -5). I am on the east coast of the US. 

Cheers, 
David
